### ISSUE TITLE
config.loadPrivateKey is not a function

### ISSUE THREAD

**Issue by yooouuri** [ToonvanStrijp/node-tikkie-checkout#2]
Hey,

`TikkieCheckoutConfig` does not have a method `loadPrivateKey`?

**Comment by yooouuri** [comment]
You removed it here https://github.com/ToonvanStrijp/node-tikkie-checkout/commit/a66dcf15b5dc595d85e3b6b19def5a931fdce2e0#diff-7e82dc7533620e594f349d3ea425b5b4L39, so I guess the example needs to be updated?

**Comment by yooouuri** [comment]
And also it looks like the API calls require an `Authorization` header?

https://developer.abnamro.com/api/tikkie-v1/technical-details

**Comment by toonvanstrijp** [comment]
@yooouuri indeed the example need to be updated.

I think you got this library/api mixed up with [https://github.com/DanielHuisman/node-tikkie](https://github.com/DanielHuisman/node-tikkie)

This library is an api client for the `tikkie fast checkout api`. This api does not require an `Authorization` header.
